### ISSUE TITLE
Når jeg åpner JanErik.html ser jeg kun tabelloverskriftene, ikke det som er lest inn fra XML-filen

### ISSUE THREAD

**Issue by h577860** [582079/ProsjektProgrammering#2]
![image](https://user-images.githubusercontent.com/42539100/46570838-0ce7c680-c96b-11e8-96e7-a6da3e66bbfc.png)

**Comment by h577860** [comment]
Ser ut som det virker i hostet versjon...

**Comment by 582079** [comment]
Det fungerer i Eclipse og Firefox for meg, også på [versjonen som er pushet](https://582079.github.io/ProsjektProgrammering/Nettside/WebContent/JanErik.html). XML filen er pushet [her](https://github.com/582079/ProsjektProgrammering/blob/master/Nettside/WebContent/Tabell.xml).

**Comment by 582079** [comment]
Beklager jeg trykket feil knapp og lukket. Vet ikke om det framdeles er et problem, hadde du hentet ned de siste endringene på github?
